import type { Receipt } from "@mcptoolshop/rf-core";
import { canonicalize } from "@mcptoolshop/rf-core";
import { RECEIPT_CSS } from "./styles.js";

/**
 * Render a receipt as a standalone HTML page.
 * No external dependencies — CSS is embedded.
 */
export function renderHtml(receipt: Receipt): string {
  const kindLabel = receipt.kind.replace(/_/g, " ");
  const title = `${capitalize(kindLabel)}: ${escHtml(receipt.subject.name)}`;
  const date = receipt.created_at.split("T")[0];

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${title}</title>
  <style>${RECEIPT_CSS}</style>
</head>
<body>
  <h1>${title}</h1>
  <blockquote>${capitalize(kindLabel)} on ${date}${receipt.environment.runner ? ` by ${escHtml(receipt.environment.runner)}` : ""}</blockquote>

  <h2>What happened</h2>
  <p>${escHtml(receipt.intent)}</p>

${renderSubject(receipt)}
${renderOutputs(receipt)}
${renderEvidence(receipt)}
${renderVerification(receipt)}

  <h2>What this does NOT prove</h2>
  <ul>
    <li>That the underlying code is correct (receipts prove process, not quality)</li>
    <li>That the CI environment itself wasn't compromised</li>
    <li>That artifacts haven't been modified after receipt creation</li>
  </ul>

  <hr>

  <details>
    <summary>Technical details</summary>

    <h3>Integrity</h3>
    <ul>
      <li><strong>ID:</strong> <code>${receipt.id}</code></li>
      <li><strong>Algorithm:</strong> ${receipt.integrity.algorithm}</li>
      <li><strong>Digest:</strong> <code>${receipt.integrity.digest}</code></li>
${receipt.integrity.signature ? `      <li><strong>Signature:</strong> <code>${escHtml(receipt.integrity.signature)}</code></li>` : ""}
    </ul>

    <h3>Environment</h3>
    <ul>
${receipt.environment.os ? `      <li><strong>OS:</strong> ${escHtml(receipt.environment.os)}</li>` : ""}
${receipt.environment.runner ? `      <li><strong>Runner:</strong> ${escHtml(receipt.environment.runner)}</li>` : ""}
${renderToolVersions(receipt)}
    </ul>

${renderPolicy(receipt)}

    <h3>Canonical JSON</h3>
    <pre><code>${escHtml(JSON.stringify(JSON.parse(canonicalize(receipt)), null, 2))}</code></pre>
  </details>

  <div class="receipt-footer">
    Generated by <a href="https://github.com/mcp-tool-shop-org/receipt-factory">receipt-factory</a>
  </div>

  <script>
  // Copy-to-clipboard for verification commands
  document.querySelectorAll('.copy-btn').forEach(btn => {
    btn.addEventListener('click', () => {
      const text = btn.getAttribute('data-copy');
      if (text) navigator.clipboard.writeText(text).then(() => {
        btn.textContent = 'Copied!';
        setTimeout(() => { btn.textContent = 'Copy'; }, 1500);
      });
    });
  });
  </script>
</body>
</html>`;
}

function renderSubject(r: Receipt): string {
  if (!r.subject.ref && !r.subject.url) return "";
  const lines: string[] = ["  <p><strong>Subject:</strong></p>", "  <ul>"];
  if (r.subject.ref) lines.push(`    <li>Ref: <code>${escHtml(r.subject.ref)}</code></li>`);
  if (r.subject.url) lines.push(`    <li>URL: <a href="${escHtml(r.subject.url)}">${escHtml(r.subject.url)}</a></li>`);
  lines.push("  </ul>", "");
  return lines.join("\n");
}

function renderOutputs(r: Receipt): string {
  if (r.outputs.length === 0) return "";
  const lines: string[] = [
    "  <h2>Results</h2>",
    "  <table>",
    "    <thead><tr><th>Output</th><th>Digest</th><th>Link</th></tr></thead>",
    "    <tbody>",
  ];
  for (const out of r.outputs) {
    const digest = out.digest ? `<code>${escHtml(truncateDigest(out.digest))}</code>` : "—";
    const link = out.url ? `<a href="${escHtml(out.url)}">link</a>` : "—";
    const size = out.size != null ? ` (${formatBytes(out.size)})` : "";
    lines.push(`    <tr><td>${escHtml(out.name)}${size}</td><td>${digest}</td><td>${link}</td></tr>`);
  }
  lines.push("    </tbody>", "  </table>", "");
  return lines.join("\n");
}

function renderEvidence(r: Receipt): string {
  if (r.evidence.length === 0) return "";
  const lines: string[] = ["  <h2>Evidence</h2>", "  <ul>"];
  for (const ev of r.evidence) {
    if (ev.url) {
      lines.push(`    <li><strong>${escHtml(ev.type)}:</strong> <a href="${escHtml(ev.url)}">${escHtml(ev.description)}</a></li>`);
    } else {
      lines.push(`    <li><strong>${escHtml(ev.type)}:</strong> ${escHtml(ev.description)}</li>`);
    }
  }
  lines.push("  </ul>", "");
  return lines.join("\n");
}

function renderVerification(r: Receipt): string {
  if (r.verification.steps.length === 0 && r.verification.commands.length === 0) return "";
  const lines: string[] = ["  <h2>How to verify</h2>"];
  if (r.verification.steps.length > 0) {
    lines.push("  <ol>");
    for (const step of r.verification.steps) {
      lines.push(`    <li>${escHtml(step)}</li>`);
    }
    lines.push("  </ol>");
  }
  if (r.verification.commands.length > 0) {
    const cmds = r.verification.commands.join("\n");
    lines.push(`  <pre><code>${escHtml(cmds)}</code></pre>`);
    lines.push(`  <button class="copy-btn" data-copy="${escAttr(cmds)}">Copy</button>`);
  }
  lines.push("");
  return lines.join("\n");
}

function renderToolVersions(r: Receipt): string {
  const entries = Object.entries(r.environment.tool_versions);
  if (entries.length === 0) return "";
  return entries
    .map(([tool, ver]) => `      <li>${escHtml(tool)}: ${escHtml(ver)}</li>`)
    .join("\n");
}

function renderPolicy(r: Receipt): string {
  if (r.policy.redacted_fields.length === 0 && r.policy.required_checks.length === 0) return "";
  const lines: string[] = ["    <h3>Policy</h3>", "    <ul>"];
  if (r.policy.redacted_fields.length > 0) {
    lines.push(`      <li><strong>Redacted:</strong> ${r.policy.redacted_fields.map(escHtml).join(", ")}</li>`);
  }
  if (r.policy.required_checks.length > 0) {
    lines.push(`      <li><strong>Required checks:</strong> ${r.policy.required_checks.map(escHtml).join(", ")}</li>`);
  }
  lines.push("    </ul>", "");
  return lines.join("\n");
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function truncateDigest(digest: string): string {
  if (digest.length <= 16) return digest;
  return digest.slice(0, 16) + "\u2026";
}

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

function escHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function escAttr(s: string): string {
  return escHtml(s).replace(/\n/g, "&#10;");
}
